#  By Jaziel Lopez (github.com/jazlopez)
#  See license file.

EXIT_NO_ERROR_CODE = 0
EXIT_ERROR_CODE = 1
EXIT_ENVIRONMENT_EXPORT_DIRECTORY_ERROR_CODE = 2
EXIT_EXPORT_DIRECTORY_ERROR_CODE = 3
EXIT_ENVIRONMENT_LOGS_DIRECTORY_ERROR_CODE = 4
EXIT_LOGS_DIRECTORY_ERROR_CODE = 5
EXIT_DIRECTORIES_MISSING_CODE = 6
